# Generated by Django 5.2.8 on 2026-04-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category__order", "order"],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                default="temp-slug", unique=True, verbose_name="URL"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="composition",
            field=models.TextField(blank=True, verbose_name="Состав"),
        ),
        migrations.AddField(
            model_name="product",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AddField(
            model_name="product",
            name="pieces",
            field=models.IntegerField(default=0, verbose_name="Количество кусочков"),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.IntegerField(default=0, verbose_name="Вес (г)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True, verbose_name="Доступен"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
    ]
