# Generated by Django 5.2.8 on 2026-04-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
