# Generated by Django 5.2.8 on 2026-04-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Промокод"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Процент"),
                            ("fixed", "Фиксированная сумма"),
                        ],
                        default="percent",
                        max_length=20,
                        verbose_name="Тип скидки",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Значение скидки"
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Минимальная сумма заказа",
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Максимальная скидка (для процентов)",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Действует с")),
                ("valid_to", models.DateTimeField(verbose_name="Действует до")),
                (
                    "max_uses",
                    models.IntegerField(
                        default=1, verbose_name="Максимум использований"
                    ),
                ),
                (
                    "used_count",
                    models.IntegerField(default=0, verbose_name="Использовано раз"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="discount",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("delivery", "Доставка"), ("pickup", "Самовывоз")],
                default="delivery",
                max_length=20,
                verbose_name="Тип доставки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Скидка"
            ),
        ),
    ]
